# Dockerfile.build
FROM node:24 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN NODE_ENV=production npm run build
RUN cp build/index.html build/404.html

FROM scratch AS export
COPY --from=builder /app/build/ /